export const STORE_INFO = {
  name: "Chi7a Store",
  nameAr: "شيحة ستور",
  slogan: "متميزون في خدمتكم",
  welcome: 'مرحبا بكم في محل "Chi7a Store" للجوال و الإلكترونيات',
  location: "قبلي، دوز، تونس",
  locationEn: "Gbeli, Douz, Tunisia",
  mapsUrl: "https://maps.app.goo.gl/zufVdGXNbm4udEqUA",
  mapsEmbedUrl:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12804.957826266513!2d9.021967236223604!3d33.46256765843268!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1256875c45255c67%3A0x4d2d7a43ff7c69cf!2sChi7a%20Store!5e1!3m2!1sen!2stn!4v1783702998037!5m2!1sen!2stn",
  phone: "+216 26 321 100",
  phoneRaw: "21626321100",
  facebook: "https://www.facebook.com/Chi7aStore",
  whatsapp: "https://wa.me/21626321100",
};

export const tunisianStates = [
  { value: "Ariana", label: "Ariana", arabic: "أريانة" },
  { value: "Beja", label: "Béja", arabic: "باجة" },
  { value: "Ben Arous", label: "Ben Arous", arabic: "بن عروس" },
  { value: "Bizerte", label: "Bizerte", arabic: "بنزرت" },
  { value: "Gabes", label: "Gabès", arabic: "قابس" },
  { value: "Gafsa", label: "Gafsa", arabic: "قفصة" },
  { value: "Jendouba", label: "Jendouba", arabic: "جندوبة" },
  { value: "Kairouan", label: "Kairouan", arabic: "القيروان" },
  { value: "Kasserine", label: "Kasserine", arabic: "القصرين" },
  { value: "Kebili", label: "Kebili", arabic: "قبلي" },
  { value: "Kef", label: "Kef", arabic: "الكاف" },
  { value: "Mahdia", label: "Mahdia", arabic: "المهدية" },
  { value: "Manouba", label: "Manouba", arabic: "منوبة" },
  { value: "Medenine", label: "Medenine", arabic: "مدنين" },
  { value: "Monastir", label: "Monastir", arabic: "المنستير" },
  { value: "Nabeul", label: "Nabeul", arabic: "نابل" },
  { value: "Sfax", label: "Sfax", arabic: "صفاقس" },
  { value: "Sidi Bouzid", label: "Sidi Bouzid", arabic: "سيدي بوزيد" },
  { value: "Siliana", label: "Siliana", arabic: "سليانة" },
  { value: "Sousse", label: "Sousse", arabic: "سوسة" },
  { value: "Tataouine", label: "Tataouine", arabic: "تطاوين" },
  { value: "Tozeur", label: "Tozeur", arabic: "توزر" },
  { value: "Tunis", label: "Tunis", arabic: "تونس" },
  { value: "Zaghouan", label: "Zaghouan", arabic: "زغوان" }
];
